---

name: Gather Pull Request Metadata
on:
  pull_request:
    types: [ opened, reopened, synchronize ]

permissions:
  contents: read

jobs:
  gather-metadata:
    runs-on: ubuntu-latest

    steps:
      - name: Repository checkout
        uses: actions/checkout@v4

      - id: Metadata
        name: Gather Pull Request Metadata
        uses: redhat-plumbers-in-action/gather-pull-request-metadata@v1
        with:
          metadata-file-name: metadata

      - name: Upload artifact with gathered metadata
        uses: actions/upload-artifact@v3
        with:
          name: Pull Request Metadata
          path: ${{ steps.Metadata.outputs.metadata-file }}

...
