---

name: Upload Artifact
on:
  pull_request:
    types: [ opened, reopened, synchronize ]

permissions:
  contents: read

jobs:
  upload-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Repository checkout
        uses: actions/checkout@v4

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: README as Artifact
          path: README.md

...
